export enum CurrentSem {
  FIRSTSEMESTER = 'FIRSTSEMESTER',

  SECOUNDSEMESTER = 'SECOUNDSEMESTER',

  THIRDSEMESTER = 'THIRDSEMESTER',

  FOURTHSEMSTER = 'FOURTHSEMSTER',

  FIFTHSEMSTER = 'FIFTHSEMSTER',

  SIXTHSEMSTER = 'SIXTHSEMSTER',

  SEVENTHSEMSTER = 'SEVENTHSEMSTER',

  EIGHTSEMSTER = 'EIGHTSEMSTER',
}
