export enum DepartmentName {
  COMPUTERSCIENCEENGINEERING = 'COMPUTERSCIENCEENGINEERING',

  ELECTRONICSANDCOMMUNICATIONALENGINEERING = 'ELECTRONICSANDCOMMUNICATIONALENGINEERING',

  ELECTRONICSANDELECTRICALENGINEERING = 'ELECTRONICSANDELECTRICALENGINEERING',

  MANAGEMENTSCINENCE = 'MANAGEMENTSCINENCE',
}
