export enum Desigination {
  ASSISTENTPROFESSOR = 'ASSISTENTPROFESSOR',

  PROFESSOR = 'PROFESSOR',

  TEACHINGASSISTENT = 'TEACHINGASSISTENT',

  RESERACHASSISTENT = 'RESERACHASSISTENT',

  GRADER = 'GRADER',
}
